---
  - include_vars: buckets.yaml

  - name: Evaluating each defined s3 bucket.
    s3_bucket:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: "{{ item.key }}"
      state: "{{ item.value.state }}"
      #policy: "{{ lookup( 'file','{{ item.key }}-policy.json', skip=true) | ternary(lookup( 'file', 'default-policy.json' ), omit) }}"
      policy: "{{ lookup('first_found', dict(files=['{{ item.key }}-policy.json'], skip=true)) | ternary(lookup('ini', 'foo section=DEFAULT file=default-policy.json'), omit) }}"
      region: "{{ item.value.region }}"
      versioning: "{{ item.value.versioning }}"
    loop:
      - "{{ lookup('dict', buckets) }}"

  - name: Setting up Lifecycle information.
    s3_lifecycle:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: "{{ item.value.bucket }}"
      expiration_days: "{{ item.value.expiration_days }}"
      prefix: "/{{ item.key }}/"
      status: "{{ item.value.status }}"
      state: "{{ item.value.state }}"
    loop:
      - "{{ lookup('dict', lifecycles) }}"

