---
groups:
  - policy:
    name: SensitiveBucketListBucket
    group:
      - devops-admin
      - client-access
    state: present
  - policy:
    name: SensitiveBucketAllowReadWrite
    group:
      - devops-admin
    state: present
  - policy:
    name: SensitiveBucketAllowReadOnly
    group:
      - client-access
    state: present