---
  - include_vars: policy_groups.yaml

  - name: Apply policies to groups.
    iam_policy:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      iam_type: group
      iam_name: "{{ item.1 }}"
      policy_name: "{{ item.0.name }}"
      state: "{{ item.0.state }}"
      policy_json: "{{ lookup( 'file', '{{ item.0.name }}-policy.json') }} "
    loop: "{{ policy_groups | subelements('group', 'skip_missing=True') }}"