---
  - include_vars: groups.yaml

  - name: Apply policies to groups.
    iam_policy:
      iam_type: group
      iam_name: "{{ item.1 }}"
      policy_name: "{{ item.0.name }}"
      state: "{{ item.0.state }}"
      policy_document: "{{ item.0.name }}-policy.json"
    loop: "{{ groups|subelements('policy.group') }}"